# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba25cb75bdea8fdf555da2aa0926406de0bd25fce627adb7d7ccf82190b1e0c0772a6b879bf5059a06fbaa93e2b7231f656c0a0e35c7713c180534074005021

test:
  secret_key_base: f07f42a6446ae0575f9661a67c5fe19062a63d50627d972c6ebb86054407b265ea32528cdf840660e4074b43b99a23f9abba3eff27dce9256401d5dd449d4327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
